### ISSUE TITLE
Firstly, thank you!

### ISSUE THREAD

**Issue by HappyCatKitten** [pilsnerbeer/multisig-tool-fixed#4]
I have some change in an an a wallet ive been wanting to move for a while now..

ok so there is a bug.. it seems some of the address calls error (none that I have outputs in) but this stops the button from changing from please wait to.. proceed..

any ideas?

![image](https://github.com/pilsnerbeer/multisig-tool-fixed/assets/1046264/f067c549-82fe-4242-b419-74b000274f29)

Thanks again, will be buying a couple of beers for you!

**Comment by pilsnerbeer** [comment]
Hi, what is the HD index value in your case? is it higher than 10? 429 indicates too many requests. If you are generating and checking a large number of addresses, this might be the issue if the API has some internal limit on how many requests can be called in a given time (I havent tested the limit myself).

**Comment by HappyCatKitten** [comment]
ah yes, its 17. im not sure why but when the wallet was created it decided to spread the HD indexes out.

I wonder if its possible to batch them with a timeout

**Comment by pilsnerbeer** [comment]
Are your funds stored at addresses above HD index 10 ? You can set the index to 10, let it run and then see if the balance is matching. I can see there is some balance found at m/8. If its all, you should be able to recover that.

**Comment by HappyCatKitten** [comment]
Funds start at 8 and finish at 17 with a total of 5 address outputs. Im not sure why coinbase decided to spread these out so sparcely.

**Comment by HappyCatKitten** [comment]
If hammering the lookup is the problem, it would be cool to get a wait function, even if they resolved over 10 minutes

**Comment by pilsnerbeer** [comment]
Uff.. so I checked it myself with HD=10 and it doesn't work either. It seems the API has introduced some limits very recently because a few weeks back everything worked fine (as reported by another user).


I just pushed an experimental fix in **429-fix** branch that addresses this issue. In this fix I introduced a slowed-down request queue with ~2 second wait, which the API seems to be Okay with (at least for now).

I checked with HD index=17 and everything loaded fine with no 429 (although it took a minute or two). Please switch from master to 429-fix branch and let me know if that worked for you. 


NOTE: The API also has an hourly limit so if you have recently used the app it might be that the hourly quota is depleted for your IP. Either wait a bit or switch IP (if you have a VPN).

**Comment by HappyCatKitten** [comment]
ok so now we arent getting any GET errors, but about 1 in 3 balances are still showing as Loading...

The JSON looks good when I inspect the GET request for those "Loading.." too.,

![image](https://github.com/pilsnerbeer/multisig-tool-fixed/assets/1046264/bbfae31e-de52-4ea7-b5ce-b339197ed9ee)

**Comment by pilsnerbeer** [comment]
by any chance, are those "Loading" addresses linked to some activity in the past? do they have non-zero balances, or previous transaction history?

**Comment by HappyCatKitten** [comment]
Yes, so it looks like "loading" occurs in 2 instances.

1. where the json contains txrefs[]
2. at first index of each of the  node path i.. IE m/0[0], m/1[0], m/2[0], m/3[0] (this occurs mostly)

**Comment by pilsnerbeer** [comment]
I see, I will try to take a closer look at this when I find some time, as I can't exactly pinpoint what's wrong right now . Thanks for reporting
